config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # root 'welcome#index'
  root to: 'welcome#index'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :articles do 
    resources :comments
  end
  
  # resources :categories

  resources :categories do 
    resources :tasks
  end

  # get '/articels' => 'articles#index'

  # get '/articles/new' => 'articles#new', as: 'new_article'
  # post '/articles' => 'articles#create', as: 'create_article'

  # get '/articles/show' => 'articles#show', as: 'articles_show'

  # get '/categories' => 'categories#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :get_article

    def index
        @comments = @article.comments
    end

    def show
        @comment = Comment.find(params[:id])
    end

    def edit
        @comment = Comment.find(params[:id])
    end

    def new
        @comment = @article.comments.build
    end

    def update
        @comment = Comment.find(params[:id])
        if @comment.update(comment_params)
            flash[:notice] = "Comment was successfully updated"
            redirect_to article_comments_path(@article.id, @comment.id)
        else
            render :edit
        end
    end 

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        flash[:notice] = "Comment was successfully deleted!"
        redirect_to article_comments_path(@article.id, @comment.id)
    end

    def create
        @comment = @article.comments.build(comment_params)
        if @comment.save
            redirect_to article_comments_path(@article.id, @comment.id)
        else
            render :new
        end
    end

    private

    def get_article
        @article = Article.find(params[:article_id])
    end

    def comment_params
        params.require(:comment).permit(:body, :article_id)
    end 

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_index.html.erb
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Body</th>
        </tr>
    </thead>

    <tbody>
        <% @comments.each do |comment| %>
            <tr>
                <td><%= comment.id %></td>
                <td><%= comment.body %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Add Comment', new_article_comment_path(@article) %> | 

app/views/comments/edit.html.erb
# <% if @article.errors.any? %>
# <h3>The following errors prevented the article from getting created</h3>
#     <ul>
#         <% @article.errors.full_messages.each do |msg|%>
#             <li><%= msg %></li>
#         <% end %>
#     </ul>
# <% end %>


<%= form_with (model: [@article, @comment], method: put) local: true do |f| %>
    <p>
        <%= f.label :name %>
        </br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :body %>
        </br>
        <%= f.text_field :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>


<%= link_to "Back to comments lists", articles_path %>

app/views/comments/index.html.erb
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Body</th>
        </tr>
    </thead>

    <tbody>
        <% @comments.each do |comment| %>
            <tr>
                <td><%= comment.id %></td>
                <td><%= comment.body %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Add Comment', new_article_comment_path(@article) %>

app/views/comments/new.html.erb
<%= form_with model: [@article, @comment], local: true do |f| %>
    <p>
        <% if @comment.errors.any? %>
            <ul>
                <% @comment.erros.full_messages.each do |message| %>
                    <li><%= message %></li>    
                <% end %>
            </ul>
        <% end %>
    </p>

    <p>
        <%= f.label :body %><br />
        <%= f.text_field :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/comments/show.html.erb
<h1>Selected Comment</h1>

<h3>Body:<%= @comment.body %></h3>

<br />



<%= link_to "Back to article lists", @comment.article %> |
# <%= link_to "Edit this category", edit_category_path(@comment) %>