config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # root 'welcome#index'
  root to: 'welcome#index'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :articles do 
    resources :comments
  end
  
  # resources :categories

  resources :categories do 
    resources :tasks
  end

  # get '/articels' => 'articles#index'

  # get '/articles/new' => 'articles#new', as: 'new_article'
  # post '/articles' => 'articles#create', as: 'create_article'

  # get '/articles/show' => 'articles#show', as: 'articles_show'

  # get '/categories' => 'categories#index'
end

app/models/task.rb
class Task < ApplicationRecord
    validates :name, presence: true, length: { minimum: 4 }

    validates :body, presence: true, length: { minimum: 5 }

    validates :task_date, presence: true

    belongs_to :category
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :set_date
  before_action :get_category
  before_action :authenticate_user!

  # GET /tasks or /tasks.json
  def index
    @tasks = @category.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = @category.tasks.build
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks or /tasks.json
  def create
    @task = @category.tasks.build(task_params)
    if @task.save
      flash[:notice] = "Task was successfully created"
      redirect_to category_path(@category.id)
    else
        render :new
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    @task = Task.find(params[:id])
      if @task.update(task_params)
          flash[:notice] = "Task was successfully updated"
          redirect_to category_path(@category.id)
      else
          render :edit
      end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
      @task = Task.find(params[:id])
      @task.destroy
      flash[:notice] = "Task was successfully deleted!"
      redirect_to category_path(@category.id)
  end

  private
    #get category
    def get_category
      @category = Category.find(params[:category_id])
    end

    #set Date
    def set_date
      @current_date = Date.today
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:category_id, :name, :body, :task_date)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with model: [@category, task], local: true do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :task_date %>
    <%= form.date_select :task_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_index.html.erb
<br />
<h1>Tasks</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Body</th>
            <th>Task Date</th>
            <th>Status</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @tasks.each do |task| %>
            <tr>
                <td><%= task.id %></td>
                <td><%= task.name %></td>
                <td><%= task.body %></td>
                <td><%= task.task_date %>
                <% if task.task_date == Date.today %>
                    <td>Due Today</td>
                <% else %>
                    <td>Not Due Today</td>
                <% end %>
                <td><%= link_to 'Show', category_task_path(@category.id, task) %></td>
                <td><%= link_to 'Edit', edit_category_task_path(@category.id, task) %></td>
                <td><%= link_to 'Delete', category_task_path(@category, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<br />
<%= link_to 'Add Task', new_category_task_path(@category) %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<td><%= link_to 'Show', category_task_path(@category.id, @task.id) %></td> |
<%= link_to 'Back', category_path(@category) %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Body</th>
      <th>Task date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.category_id %></td>
        <td><%= task.name %></td>
        <td><%= task.body %></td>
        <td><%= task.task_date %></td>
        <td><%= link_to 'Show', category_task_path(@category.id, task) %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', categories_path(@category) %> |
<%= link_to 'New Task', new_category_task_path(@category) %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_with model: [@category, @task], local: true do |f| %>
        <p>
            <% if @task.errors.any? %>
                <ul>
                    <% @task.errors.full_messages.each do |message| %>
                        <li><%= message %></li>    
                    <% end %>
                </ul>
            <% end %>
        </p>
    <br />
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <br />
    <div>   
        <%= f.label :body %>
        <%= f.text_field :body %>
    </div>
    <br />
    <div class="field">
        <%= f.label :task_date %>
        <%= f.date_select :task_date %>
    </div>
    <br />
    <p>
        <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', category_path(@category) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @task.category_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @task.body %>
</p>

<p>
  <strong>Task date:</strong>
  <%= @task.task_date %>
</p>


<%= link_to 'Edit', edit_category_task_path %> |
<%= link_to 'Back', category_path(@category) %>