config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # root 'welcome#index'
  root to: 'welcome#index'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :articles do 
    resources :comments
  end
  
  # resources :categories

  resources :categories do 
    resources :tasks
  end

  # get '/articels' => 'articles#index'

  # get '/articles/new' => 'articles#new', as: 'new_article'
  # post '/articles' => 'articles#create', as: 'create_article'

  # get '/articles/show' => 'articles#show', as: 'articles_show'

  # get '/categories' => 'categories#index'
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true, uniqueness: true,
                    format: { with: /\A[a-zA-Z]+\z/, message: "Only allows letters. Spacing is not allowed!" },
                    length: { minimum: 4 }

    validates :body, presence: true, length: { minimum: 10 }

    has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
       @article = Article.find(params[:id])
       @comments = @article.comments
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        # @article.name = params[:name]
        # @article.body = params[:body]

        if @article.save
            flash[:notice] = "Article was successfully created!"
            redirect_to articles_path(@article)
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render :edit
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:notice] = "Article was successfully deleted!"
        redirect_to articles_path
    end

    private
    def article_params
        params.require(:article).permit(:name, :body)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h3>The following errors prevented the article from getting created</h3>
    <ul>
        <% @article.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>


<%= form_for @article do |f| %>
    <p>
        <%= f.label :name %>
        </br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :body %>
        </br>
        <%= f.text_field :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>


<%= link_to "Back to article lists", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Body</th>
            <th>Edit</th>
            <th>View</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.id %></td>
                <td><%= article.name %></td>
                <td><%= article.body %></td>
                <td>| <%= link_to 'Edit', edit_article_path(article) %>|</td>
                <td>|<%= link_to 'Show', article_path(article) %>|</td>
                <td>|<%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %>|</td>
            </tr>
        <% end %>
    </tbody>
</table>
<p><%= link_to 'New Article', new_article_path%></p>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Selected Article</h1>
<h3>Name:<%= @article.name %></h3>
<h3>Body:<%= @article.body %></h3>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Body</th>
        </tr>
    </thead>

    <tbody>
        <% @comments.each do |comment| %>
            <tr>
                <td><%= comment.id %></td>
                <td><%= comment.body %></td>
                <td><%= link_to 'Edit', edit_article_comment_path(@article.id, comment) %>Edit</td>
            </tr>
        <% end %>
    </tbody>
</table>


Partial:
<%= render 'comments/index', comments: @comments %>

<%= link_to 'Add Comment', new_article_comment_path(@article) %> 
| <%= link_to "Back to article lists", articles_path %> |
<%= link_to "Edit this article", edit_article_path(@article) %>